#!/bin/sh


#LAUNCHERS
$HOME/.config/bspwm/autostart.sh


bspc config border_width          3
bspc config window_gap            10
bspc config top_padding           30
bspc config single_monocle        false
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config click_to_focus	 true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp state=fullscreen
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a Gnome-disks state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen


bspc rule -a Xfce4-appfinder  state=floating sticky=on
bspc rule -a Gpick state=floating sticky=on
bspc rule -a mpv state=floating sticky=on
#bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a feh state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Arandr state=floating
bspc rule -a Galculator state=floating
bspc rule -a Font-manager state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Peek state=floating
bspc rule -a Skype state=floating


###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
